#!/bin/bash

function _set_theme(){
  cd ~/.config/xfce4/terminal
  grep -Fxvf <(cat /usr/share/xfce4/terminal/colorschemes/*.theme) terminalrc > .terminalrc.tmp
  grep -v -e Name -e Scheme "/usr/share/xfce4/terminal/colorschemes/$1.theme" >> .terminalrc.tmp
  cp terminalrc terminalrc.bak
  mv .terminalrc.tmp terminalrc
}

if [ $(xfconf-query list -c xsettings -p /Net/ThemeName) = 'Xfce-dawn' ]
then
	#xfconf-query -c xsettings -p /Net/ThemeName -s 'Xfce-dusk'
	xfconf-query -c xsettings -p /Net/ThemeName -s 'Adwaita-dark'
	echo 'okdusk'
    #_set_theme 'solarized-dark'
    _set_theme 'dark-pastels'
	exit
fi

if [ $(xfconf-query list -c xsettings -p /Net/ThemeName) = 'Adwaita-dark' ]
then
	xfconf-query -c xsettings -p /Net/ThemeName -s 'Xfce-dawn'
	echo  'okdawn'
    #_set_theme 'solarized-light'
    _set_theme 'black-on-white'
	exit
fi

